/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import database.IinformationController;
import database.transactions.AccountInformation;
import database.transactions.passwordChange;
import gui.Settings.ActionSettings;
import gui.Settings.Dialogs;
import gui.Settings.IRegulator;
import gui.Settings.TextSettings;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;

/**
 *
 * @author pc
 */
public class ChangePasswordScreen extends javax.swing.JFrame implements IRegulator,IinformationController{
private passwordChange passwChangeObject=null;
    /**
     * Creates new form ChangePasswordScreen
     */
    public ChangePasswordScreen() {
        initComponents();
        getedits();
    }

    public passwordChange getPasswChangeObject() {
        if (this.passwChangeObject==null) {
            passwChangeObject=new passwordChange();
        }
        return passwChangeObject;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        passwordPagePanel = new javax.swing.JPanel();
        btnOk = new javax.swing.JLabel();
        lblNameSurname3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtPhoneNumber = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtIdentity = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSecurtiyAns = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtOldPassword = new javax.swing.JPasswordField();
        txtNewPasswordAgain = new javax.swing.JPasswordField();
        txtNewPassword = new javax.swing.JPasswordField();
        btnChange = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        passwordPagePanel.setBackground(new java.awt.Color(102, 0, 0));

        btnOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/Back.png"))); // NOI18N
        btnOk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOkMouseClicked(evt);
            }
        });

        lblNameSurname3.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lblNameSurname3.setForeground(new java.awt.Color(255, 255, 255));
        lblNameSurname3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNameSurname3.setText("PASSWORD PAGE");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("IDENTITY NO:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PHONE NO:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SECURİTY ANS:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("OLD PASSWORD:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("NEW PASSWORD:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("NEW PASSWORD AGAIN:");

        btnChange.setBackground(new java.awt.Color(255, 204, 0));
        btnChange.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnChange.setForeground(new java.awt.Color(255, 255, 255));
        btnChange.setText("CHANGE");
        btnChange.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout passwordPagePanelLayout = new javax.swing.GroupLayout(passwordPagePanel);
        passwordPagePanel.setLayout(passwordPagePanelLayout);
        passwordPagePanelLayout.setHorizontalGroup(
            passwordPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, passwordPagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(passwordPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, passwordPagePanelLayout.createSequentialGroup()
                        .addGroup(passwordPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, passwordPagePanelLayout.createSequentialGroup()
                                .addComponent(btnOk)
                                .addGap(92, 92, 92)
                                .addComponent(lblNameSurname3))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, passwordPagePanelLayout.createSequentialGroup()
                                .addGroup(passwordPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addGroup(passwordPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel4)))
                                .addGap(18, 18, 18)
                                .addGroup(passwordPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtOldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNewPasswordAgain, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(passwordPagePanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(passwordPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(passwordPagePanelLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(passwordPagePanelLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtIdentity, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnChange, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(passwordPagePanelLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtSecurtiyAns, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(40, 40, 40))
        );

        passwordPagePanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtIdentity, txtNewPassword, txtNewPasswordAgain, txtOldPassword, txtPhoneNumber, txtSecurtiyAns});

        passwordPagePanelLayout.setVerticalGroup(
            passwordPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passwordPagePanelLayout.createSequentialGroup()
                .addGroup(passwordPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(passwordPagePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnOk))
                    .addGroup(passwordPagePanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lblNameSurname3)))
                .addGap(29, 29, 29)
                .addGroup(passwordPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIdentity, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(passwordPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(passwordPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSecurtiyAns, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(passwordPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(passwordPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(passwordPagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtNewPasswordAgain, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnChange, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        passwordPagePanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnChange, txtIdentity, txtNewPassword, txtNewPasswordAgain, txtOldPassword, txtPhoneNumber, txtSecurtiyAns});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(passwordPagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(passwordPagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOkMouseClicked
        if (isEnabledOldPassword()) {
            ActionSettings.setVisible(this, new SettingsScreen());       
        }else{
            ActionSettings.setVisible(this, new LoginScreen());  
        }
         
    }//GEN-LAST:event_btnOkMouseClicked

    private void btnChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeActionPerformed
        if (this.informationIsValid()) {
            this.changePassword();
        }else{
            Dialogs.spaceError(this);
        }
         
    }//GEN-LAST:event_btnChangeActionPerformed
private void changePassword(){
    String newPassword=String.valueOf(this.txtNewPassword.getPassword());
      String newPasswordAgain=String.valueOf(this.txtNewPasswordAgain.getPassword());
      if (newPassword.equals(newPasswordAgain)) {
        this.passwordOkey();
    }else{
          Dialogs.showPrivateMessage(this, "Passwords do not match \n please try again!");
      }
}
private void passwordOkey(){
   this.getPasswChangeObject().setIdentityNumber(this.txtIdentity.getText());
      this.getPasswChangeObject().setPhoneNumber(this.txtPhoneNumber.getText());
         this.getPasswChangeObject().setSecurityAns(this.txtSecurtiyAns.getText());
        if (this.isEnabledOldPassword()) {
           this.getPasswChangeObject().setOldPassword(String.valueOf(this.txtOldPassword.getPassword()));
    }
   this.getPasswChangeObject().setNewPassword(String.valueOf(this.txtNewPassword.getPassword()));
    if (this.getPasswChangeObject().passwordIsChanged()) {
           Dialogs.showPrivateMessage(this, "Your password is change be successfully !");
           if (this.isEnabledOldPassword()) {
               ActionSettings.setVisible(this, new ChangePasswordScreen());
                          
        }else{
               ActionSettings.setVisible(this, new LoginScreen());
           }
    }else{
        Dialogs.showPrivateMessage(this, "Your password could not be renewed \n  please check your information.");
    }
}
    @Override
    public void getedits() {
        this.setLocationRelativeTo(null);
        passwordPagePanel.setFocusable(true);
        TextSettings.setOnlyNumber(txtIdentity);
        TextSettings.setMaxLimit(txtIdentity, 11);
        TextSettings.setOnlyNumber(txtPhoneNumber);
        TextSettings.setMaxLimit(txtPhoneNumber, 11);
        if (accountInformation().getUserID()==0) {
            this.txtOldPassword.setEnabled(false);
        }
    }
    public JPasswordField getOldPasswordText(){
        return txtOldPassword;
    }
    
    private boolean isEnabledOldPassword(){
        return this.getOldPasswordText().isEnabled();
    }

    @Override
    public boolean informationIsValid() {
return TextSettings.textAreaIsEmpty(this.passwordPagePanel);
    }

    @Override
    public AccountInformation accountInformation() {
       return AccountInformation.getInstace();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePasswordScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePasswordScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePasswordScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePasswordScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangePasswordScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChange;
    private javax.swing.JLabel btnOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblNameSurname3;
    private javax.swing.JPanel passwordPagePanel;
    private javax.swing.JTextField txtIdentity;
    private javax.swing.JPasswordField txtNewPassword;
    private javax.swing.JPasswordField txtNewPasswordAgain;
    private javax.swing.JPasswordField txtOldPassword;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtSecurtiyAns;
    // End of variables declaration//GEN-END:variables
}
