/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import database.IinformationController;
import database.transactions.AccountInformation;
import database.transactions.DepositMoney;
import gui.Settings.ActionSettings;
import gui.Settings.Dialogs;
import gui.Settings.IRegulator;
import gui.Settings.TextSettings;
import javax.swing.JOptionPane;


public class DepositScreen extends javax.swing.JFrame implements IRegulator,IinformationController{
private int deposit=0;
   private  DepositMoney depositMoneyObject=null;
    public DepositScreen() {
        initComponents();
           getedits();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DepositPanel = new javax.swing.JPanel();
        lblNameSurname3 = new javax.swing.JLabel();
        lbl10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbl11 = new javax.swing.JLabel();
        userBalanceLabel = new javax.swing.JLabel();
        lbl12 = new javax.swing.JLabel();
        txtDeposit = new javax.swing.JTextField();
        btnOK = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        userNameSurnameLabel = new javax.swing.JLabel();
        btnOk = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        DepositPanel.setBackground(new java.awt.Color(102, 51, 0));
        DepositPanel.setForeground(new java.awt.Color(102, 0, 102));

        lblNameSurname3.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lblNameSurname3.setForeground(new java.awt.Color(255, 255, 255));
        lblNameSurname3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNameSurname3.setText("DEPOSIT PAGE");

        lbl10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl10.setForeground(new java.awt.Color(255, 255, 255));
        lbl10.setText("A maximum of 40.000 TL can be deposit at a time.");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/Exclamation Point Key.png"))); // NOI18N

        lbl11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl11.setForeground(new java.awt.Color(255, 255, 255));
        lbl11.setText("BALANCE:");

        userBalanceLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        userBalanceLabel.setForeground(new java.awt.Color(255, 255, 255));
        userBalanceLabel.setText("[BALANCE]");

        lbl12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl12.setForeground(new java.awt.Color(255, 255, 255));
        lbl12.setText("AMOUNT TO BE DEPOSIT:");

        txtDeposit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDepositKeyReleased(evt);
            }
        });

        btnOK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/OK Button.png"))); // NOI18N
        btnOK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/Card Payment.png"))); // NOI18N

        userNameSurnameLabel.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        userNameSurnameLabel.setForeground(new java.awt.Color(255, 255, 255));
        userNameSurnameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userNameSurnameLabel.setText("[USER NAME AND SURNAME]");

        btnOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/Back.png"))); // NOI18N
        btnOk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOkMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout DepositPanelLayout = new javax.swing.GroupLayout(DepositPanel);
        DepositPanel.setLayout(DepositPanelLayout);
        DepositPanelLayout.setHorizontalGroup(
            DepositPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DepositPanelLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(DepositPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DepositPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(userNameSurnameLabel)
                        .addGroup(DepositPanelLayout.createSequentialGroup()
                            .addComponent(lbl11)
                            .addGap(18, 18, 18)
                            .addComponent(userBalanceLabel))
                        .addGroup(DepositPanelLayout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lbl12)
                            .addGap(18, 18, 18)
                            .addComponent(txtDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(DepositPanelLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl10)))
                .addGap(48, 48, 48))
            .addGroup(DepositPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnOk)
                .addGap(134, 134, 134)
                .addComponent(lblNameSurname3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DepositPanelLayout.setVerticalGroup(
            DepositPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DepositPanelLayout.createSequentialGroup()
                .addGroup(DepositPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DepositPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnOk))
                    .addGroup(DepositPanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lblNameSurname3)))
                .addGap(38, 38, 38)
                .addComponent(userNameSurnameLabel)
                .addGap(33, 33, 33)
                .addGroup(DepositPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl11)
                    .addComponent(userBalanceLabel))
                .addGap(34, 34, 34)
                .addGroup(DepositPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DepositPanelLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(DepositPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(DepositPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbl12)
                                .addComponent(txtDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel11))
                .addGroup(DepositPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DepositPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl10)
                        .addGap(63, 63, 63))
                    .addGroup(DepositPanelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel9)
                        .addContainerGap(47, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DepositPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DepositPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void getedits() {
        this.setLocationRelativeTo(null);
        DepositPanel.setFocusable(true);
        TextSettings.setOnlyNumber(txtDeposit);
        TextSettings.setMaxLimit(txtDeposit, 5);
        this.userNameSurnameLabel.setText(accountInformation().getNameSurname());
        this.userBalanceLabel.setText(String.valueOf(accountInformation().getBalance()));
    }

    @Override
    public boolean informationIsValid() {
        return!(this.txtDeposit.getText().equals(""));
    }

    @Override
    public AccountInformation accountInformation() {
        return AccountInformation.getInstace();
    }

    public DepositMoney getDepositMoneyObject() {
        if (depositMoneyObject==null) {
            depositMoneyObject=new DepositMoney();
        }
        return depositMoneyObject;
    }

    
    private void txtDepositKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDepositKeyReleased
        this.deposit=TextSettings.checkTheKeyReleased(txtDeposit, 40000);
        System.out.println(deposit);
    }//GEN-LAST:event_txtDepositKeyReleased

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        if (informationIsValid()) {
            this.depositMoney();
        }else{
            Dialogs.spaceError(this);
        }

    }//GEN-LAST:event_btnOKActionPerformed
private void depositMoney() {
    this.getDepositMoneyObject().setAmountToBeDeposit(this.deposit);
    if (getDepositMoneyObject().moneyBeenDeposit()) {
         Dialogs.showPrivateMessage(this, "The transaction was successful\n deposited amount:"+this.deposit+"TL");
    ActionSettings.setVisible(this, new DepositScreen());
    }else{
        Dialogs.showPrivateMessage(this, "undefined amount! \nplease check the amount.");
    }
}
    private void btnOkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOkMouseClicked
        ActionSettings.setVisible(this, new AccountScreen());
    }//GEN-LAST:event_btnOkMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DepositScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DepositScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DepositScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DepositScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DepositScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DepositPanel;
    private javax.swing.JButton btnOK;
    private javax.swing.JLabel btnOk;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbl10;
    private javax.swing.JLabel lbl11;
    private javax.swing.JLabel lbl12;
    private javax.swing.JLabel lblNameSurname3;
    private javax.swing.JTextField txtDeposit;
    private javax.swing.JLabel userBalanceLabel;
    private javax.swing.JLabel userNameSurnameLabel;
    // End of variables declaration//GEN-END:variables
}
