/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import database.IinformationController;
import database.transactions.AccountInformation;
import database.transactions.withDrawal;
import gui.Settings.ActionSettings;
import gui.Settings.Dialogs;
import gui.Settings.IRegulator;
import gui.Settings.TextSettings;
import javax.swing.JOptionPane;

/**
 *
 * @author pc
 */
public class WithDrawalScreen extends javax.swing.JFrame implements IRegulator,IinformationController {
private withDrawal withDrawalObject=null;
    
    private int Amount=0;
    /**
     * Creates new form WithDrawalScreen
     */
    public WithDrawalScreen() {
        initComponents();
        getedits();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        WithDrawalPanel = new javax.swing.JPanel();
        lblNameSurname = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        txtBalance = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        txtWithDrawnAmount = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtNameSurname = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        WithDrawalPanel.setBackground(new java.awt.Color(102, 0, 102));
        WithDrawalPanel.setForeground(new java.awt.Color(102, 0, 102));

        lblNameSurname.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lblNameSurname.setForeground(new java.awt.Color(255, 255, 255));
        lblNameSurname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNameSurname.setText("WITHDRAWAL PAGE");

        lbl2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl2.setForeground(new java.awt.Color(255, 255, 255));
        lbl2.setText("A maximum of 5000 TL can be withdrawn at a time.");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/Exclamation Point Key.png"))); // NOI18N

        lbl1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl1.setForeground(new java.awt.Color(255, 255, 255));
        lbl1.setText("BALANCE:");

        txtBalance.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtBalance.setForeground(new java.awt.Color(255, 255, 255));
        txtBalance.setText("[BALANCE]");

        lbl3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl3.setForeground(new java.awt.Color(255, 255, 255));
        lbl3.setText("AMOUNT TO BE WITHDRAWN:");

        txtWithDrawnAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtWithDrawnAmountKeyReleased(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/OK Button.png"))); // NOI18N
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/Card Payment.png"))); // NOI18N

        txtNameSurname.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        txtNameSurname.setForeground(new java.awt.Color(255, 255, 255));
        txtNameSurname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtNameSurname.setText("[USER NAME AND SURNAME]");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/icons/Back.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout WithDrawalPanelLayout = new javax.swing.GroupLayout(WithDrawalPanel);
        WithDrawalPanel.setLayout(WithDrawalPanelLayout);
        WithDrawalPanelLayout.setHorizontalGroup(
            WithDrawalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WithDrawalPanelLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(WithDrawalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WithDrawalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtNameSurname)
                        .addGroup(WithDrawalPanelLayout.createSequentialGroup()
                            .addComponent(lbl1)
                            .addGap(18, 18, 18)
                            .addComponent(txtBalance))
                        .addGroup(WithDrawalPanelLayout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lbl3)
                            .addGap(18, 18, 18)
                            .addComponent(txtWithDrawnAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(WithDrawalPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl2)))
                .addGap(48, 48, 48))
            .addGroup(WithDrawalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(134, 134, 134)
                .addComponent(lblNameSurname)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        WithDrawalPanelLayout.setVerticalGroup(
            WithDrawalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WithDrawalPanelLayout.createSequentialGroup()
                .addGroup(WithDrawalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(WithDrawalPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(WithDrawalPanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lblNameSurname)))
                .addGap(38, 38, 38)
                .addComponent(txtNameSurname)
                .addGap(33, 33, 33)
                .addGroup(WithDrawalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl1)
                    .addComponent(txtBalance))
                .addGap(34, 34, 34)
                .addGroup(WithDrawalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(WithDrawalPanelLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(WithDrawalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(WithDrawalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbl3)
                                .addComponent(txtWithDrawnAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel7))
                .addGroup(WithDrawalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(WithDrawalPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl2)
                        .addGap(63, 63, 63))
                    .addGroup(WithDrawalPanelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel3)
                        .addContainerGap(50, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(WithDrawalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(WithDrawalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtWithDrawnAmountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtWithDrawnAmountKeyReleased
       this.Amount=TextSettings.checkTheKeyReleased(txtWithDrawnAmount, 5000);
        System.out.println(Amount);

    }//GEN-LAST:event_txtWithDrawnAmountKeyReleased

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
       ActionSettings.setVisible(this, new AccountScreen());
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (this.informationIsValid()) {
            this.giveMoney();
        }else{
            Dialogs.spaceError(this);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed
private void giveMoney(){
    this.getWithDrawalObject().setAmount(Amount);
    if (getWithDrawalObject().isWithDrawal()) {
        Dialogs.showPrivateMessage(this, "transaction completed \n amount withdrawn:"+this.Amount+"TL");
        ActionSettings.setVisible(this, new WithDrawalScreen());
    }else{
        Dialogs.showPrivateMessage(this, "sorry your balance is insufficient !");
    }
}
    @Override
    public void getedits() {
        this.setLocationRelativeTo(null);
        WithDrawalPanel.setFocusable(true);
        TextSettings.setOnlyNumber(txtWithDrawnAmount);
        TextSettings.setMaxLimit(txtWithDrawnAmount, 4);
        this.txtNameSurname.setText(accountInformation().getNameSurname());
        this.txtBalance.setText(String.valueOf(this.accountInformation().getBalance()));
    }

    @Override
    public boolean informationIsValid() {
        return !(this.txtWithDrawnAmount.getText().equals(""));
    }

    @Override
    public AccountInformation accountInformation() {
        return AccountInformation.getInstace();
    }

    public withDrawal getWithDrawalObject() {
        if (this.withDrawalObject==null) {
            withDrawalObject=new withDrawal();
        }
        return withDrawalObject;
    }

  

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WithDrawalScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WithDrawalScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WithDrawalScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WithDrawalScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WithDrawalScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel WithDrawalPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lblNameSurname;
    private javax.swing.JLabel txtBalance;
    private javax.swing.JLabel txtNameSurname;
    private javax.swing.JTextField txtWithDrawnAmount;
    // End of variables declaration//GEN-END:variables
}
